name: Deploy Portifólio
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to main
        uses: actions/checkout@v1
      - name: install dependencies
        run: composer install
      - name: Deploy para host Hostinger
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          TARGET: ${{secrets.REMOTE_TARGET_PORTIFOLIO}}